# GitHub Repository metadata
url: vcl-dashboards-non-interactive-export
website: https://docs.devexpress.com/VCL/405642/ExpressDashboards/vcl-dashboards
description: Generate DevExpress VCL Dashboards in backend and service applications.
tags: [vcl, pdf, dashboards, backend, service, cli, console]
